---
title: "Statistical methods to "
subtitle: "How differences in polls pf the 2024 US election can be used make predictions"
author: 
  - Daniel 
  - Vandan
  - Dennis
thanks: "Code and data are available at: [https://github.com/possibleburger2/](https://github.com/possibleburger2/temporary)."
date: today
date-format: long
abstract: "Using polls of polls "
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
library(tidyverse)
library(knitr)
library(kableExtra)
library(readr)
library(dplyr)
```


# Introduction

Overview paragraph

Estimand paragraph

Results paragraph

Why it matters paragraph

Telegraphing paragraph: The remainder of this paper is structured as follows. @sec-data....






# Data {#sec-data}

## Overview

We use the statistical programming language R [@citeR].... Our data.... Following @tellingstories, we consider...

Overview text

## Measurement
	


## Outcome variables



## Predictor variables

Add graphs, tables and text.

Use sub-sub-headings for each outcome variable and feel free to combine a few into one if they go together naturally.



# Model {#set-model}
Explain why model we chose over something like linear
We want to include polls with different methodology 
Test impact different poll measures have on the model
Reduce weighting or eliminate polls with partisan influence (endorsement, sponsorship etc)



## Model set-up


pollscore: A numeric value representing the score or reliability of the pollster in question (e.g., -1.1). "The error and bias we can attribute to a pollster. Negative numbers are better. Stands for "Predictive Optimization of Latent skill Level in Surveys, Considering Overall Record, Empirically.

numeric_grade: A numeric rating given to the pollster to indicate their quality or reliability (e.g., 3.0).

methodology: The method used to conduct the poll (e.g., Online Panel).

transparency_score: A score reflecting the pollster’s transparency about their methodology (e.g., 9.0). "A grade for how transparent a pollster is, calculated based on how much information it discloses about its polls and weighted by 
by recency. The highest Transparency Score is 10."

We run the model in R [@citeR].



\newpage

\appendix

# Appendix {-}

Idealized poll

Mixed mode polling: systematic phone polling, location based online polling, dont know if practical or expensive but maybe real life geographical polling?
Make sure polls are done in locations where outcomes matter, dont over poll high density one sided areas
Only use financial incentive if possible, thinking about non response bias



\newpage


# References

